openapi: 3.0.0
info:
  title: Campaign API
  description: API for retrieving current running campaigns.
  version: 1.0.0
paths:
  /campaigns:
    get:
      summary: Retrieve current running campaigns
      responses:
        '200':
          description: A list of current running campaigns
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CampaignResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: "Bad request"
    CampaignResponse:
      type: object
      properties:
        game:
          type: string
          example: "mygame"
        name:
          type: string
          example: "mycampaign"
        priority:
          type: number
          format: double
          example: 10.5
        matchers:
          type: object
          properties:
            level:
              type: object
              properties:
                min:
                  type: integer
                  example: 1
                max:
                  type: integer
                  example: 3
            has:
              type: object
              properties:
                country:
                  type: array
                  items:
                    type: string
                  example: ["US", "RO", "CA"]
                items:
                  type: array
                  items:
                    type: string
                  example: ["item_1"]
            does_not_have:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: string
                  example: ["item_4"]
        start_date:
          type: string
          format: date-time
          example: "2022-01-25T00:00:00Z"
        end_date:
          type: string
          format: date-time
          example: "2022-02-25T00:00:00Z"
        enabled:
          type: boolean
          example: true
        last_updated:
          type: string
          format: date-time
          example: "2021-07-13T11:46:58Z"